# Generated by Django 5.2.12 on 2026-07-17 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_category_color_coupon_fabric_order_product_orderitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='store.color'),
        ),
    ]
