# Generated by Django 5.2.12 on 2026-07-17 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_productimage_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='size',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
