# Generated by Django 5.2.12 on 2026-07-17 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_productimage_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.TextField(),
        ),
    ]
