# Generated by Django 5.1.4 on 2026-07-24 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_product_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='PincodeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pincode', models.CharField(max_length=10, unique=True)),
                ('state', models.CharField(blank=True, default='', max_length=100)),
                ('city', models.CharField(blank=True, default='', max_length=100)),
                ('zone', models.CharField(choices=[('metro', 'Metro / Tier 1'), ('regional', 'Regional State'), ('national', 'National'), ('remote', 'Remote / Special')], default='national', max_length=50)),
                ('standard_rate', models.DecimalField(decimal_places=2, default=99, max_digits=8)),
                ('express_rate', models.DecimalField(decimal_places=2, default=199, max_digits=8)),
                ('estimated_days', models.CharField(default='3-5 Days', max_length=50)),
                ('is_serviceable', models.BooleanField(default=True)),
                ('cod_available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShippingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('free_shipping_threshold', models.DecimalField(decimal_places=2, default=1999, max_digits=10)),
                ('standard_flat_rate', models.DecimalField(decimal_places=2, default=99, max_digits=10)),
                ('express_flat_rate', models.DecimalField(decimal_places=2, default=199, max_digits=10)),
                ('shiprocket_enabled', models.BooleanField(default=False)),
                ('shiprocket_email', models.CharField(blank=True, default='', max_length=200)),
                ('shiprocket_password', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Shipping Configuration',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='courier_name',
            field=models.CharField(blank=True, default='Standard Courier', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_type',
            field=models.CharField(default='standard', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='estimated_delivery_days',
            field=models.CharField(blank=True, default='3-5 Business Days', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
