# Generated by Django 5.1.4 on 2026-07-24 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_pincoderate_shippingconfig_order_courier_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingconfig',
            name='dtdc_api_key',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='shippingconfig',
            name='dtdc_customer_code',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='shippingconfig',
            name='primary_courier',
            field=models.CharField(choices=[('dtdc', 'DTDC Express Courier'), ('shiprocket', 'Shiprocket Aggregator API'), ('delhivery', 'Delhivery Express'), ('manual', 'Custom Rule Engine')], default='dtdc', max_length=50),
        ),
    ]
