# Generated by Django 5.1.4 on 2026-07-24 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_shippingconfig_dtdc_api_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingconfig',
            name='delhivery_api_key',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='shippingconfig',
            name='delhivery_client_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='shippingconfig',
            name='primary_courier',
            field=models.CharField(choices=[('one_delhivery', 'one.delhivery Logistics Platform'), ('dtdc', 'DTDC Express Courier'), ('shiprocket', 'Shiprocket Aggregator API'), ('manual', 'Custom Rule Engine')], default='one_delhivery', max_length=50),
        ),
    ]
