# Generated by Django 5.1.4 on 2026-07-24 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_shippingconfig_delhivery_api_key_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razorpay_enabled', models.BooleanField(default=True)),
                ('razorpay_mode', models.CharField(choices=[('test', 'Test / Sandbox Mode'), ('live', 'Production / Live Mode')], default='test', max_length=20)),
                ('razorpay_key_id', models.CharField(blank=True, default='', max_length=200)),
                ('razorpay_key_secret', models.CharField(blank=True, default='', max_length=200)),
                ('razorpay_webhook_secret', models.CharField(blank=True, default='', max_length=200)),
                ('cod_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Payment Gateway Configuration',
            },
        ),
    ]
